#!/usr/bin/env python3
from __future__ import annotations

import sys
from datetime import UTC, date, datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT), str(ROOT / "packages"), str(ROOT / "apps"), str(ROOT / "workers"), str(ROOT / "sources")]

from sqlalchemy import select  # noqa: E402

from database.models import Company, SavedView  # noqa: E402
from database.session import SessionLocal  # noqa: E402
from models.enums import FundingStage, RemotePolicy  # noqa: E402
from models.raw_company import RawCompany, RawFundingRound, RawInvestor, RawJob  # noqa: E402
from workers.scraping.ingest import ingest_raw_company  # noqa: E402


def d(days: int) -> date:
    return date.today() - timedelta(days=days)


def dt(days: int, hours: int = 8) -> datetime:
    return datetime.now(UTC) - timedelta(days=days, hours=hours)


def companies() -> list[RawCompany]:
    return [
        RawCompany(
            external_id="northwind-labs",
            source_name="ycombinator",
            source_url="https://www.ycombinator.com/companies/northwind-labs",
            confidence=0.95,
            name="Northwind Labs",
            short_description="AI code review that catches production incidents before merge.",
            description="Northwind Labs builds an AI code-review platform for growing engineering teams. The company is fully remote and hiring backend and ML engineers after a recent seed round.",
            website_url="https://www.northwindlabs.dev",
            careers_url="https://www.northwindlabs.dev/careers",
            jobs_url="https://www.northwindlabs.dev/jobs",
            linkedin_url="https://www.linkedin.com/company/northwind-labs",
            github_url="https://github.com/northwind-labs",
            yc_url="https://www.ycombinator.com/companies/northwind-labs",
            headquarters_country="United States",
            headquarters_city="San Francisco",
            headquarters_continent="North America",
            founded_date=d(220),
            funding_stage=FundingStage.SEED,
            funding_rounds=[
                RawFundingRound(
                    round_type="seed",
                    amount=4_200_000,
                    currency="USD",
                    amount_usd=4_200_000,
                    announced_date=d(12),
                    investors=[
                        RawInvestor(name="Y Combinator", investor_type="accelerator", is_lead=True),
                        RawInvestor(name="Sequoia", investor_type="vc"),
                    ],
                    lead_investors=["Y Combinator"],
                    source="ycombinator",
                )
            ],
            investors=[
                RawInvestor(name="Y Combinator", investor_type="accelerator", is_lead=True),
                RawInvestor(name="Sequoia", investor_type="vc"),
            ],
            employee_range="11-50",
            employee_count_min=11,
            employee_count_max=50,
            estimated_employee_count=18,
            founders=["Maya Chen", "Omar Haddad"],
            primary_industry="Developer Tools",
            industries=["Developer Tools", "AI", "Security"],
            business_model=["SaaS", "Developer Tools", "AI"],
            frontend_technologies=["React", "Next.js"],
            backend_technologies=["Python", "FastAPI"],
            programming_languages=["Python", "TypeScript"],
            frameworks=["Next.js", "FastAPI", "LangChain"],
            databases=["PostgreSQL", "Redis"],
            cloud_providers=["AWS"],
            ai_technologies=["OpenAI", "LangChain"],
            devops_technologies=["Docker", "Kubernetes"],
            tech_stack_confidence=0.8,
            remote_policy=RemotePolicy.GLOBAL_REMOTE,
            remote_policy_text="Work from anywhere. Distributed team, async-first.",
            remote_evidence_url="https://www.northwindlabs.dev/careers",
            remote_confidence=0.9,
            jobs=[
                RawJob(title="Senior Backend Engineer", role_category="backend", location="Worldwide", remote_type="global_remote", job_url="https://www.northwindlabs.dev/jobs/backend", source="ycombinator"),
                RawJob(title="ML Engineer", role_category="machine_learning", location="Worldwide", remote_type="global_remote", job_url="https://www.northwindlabs.dev/jobs/ml", source="ycombinator"),
            ],
            source_urls=["https://www.ycombinator.com/companies/northwind-labs"],
            discovered_at=dt(0, 2),
        ),
        RawCompany(
            external_id="atlasflow",
            source_name="index_ventures",
            source_url="https://www.indexventures.com/companies/atlasflow",
            confidence=0.85,
            name="Atlasflow",
            short_description="Workflow automation for operations teams at B2B SaaS companies.",
            description="Atlasflow helps revenue and operations teams automate messy handoffs between CRM, billing, and support tools.",
            website_url="https://atlasflow.app",
            careers_url="https://atlasflow.app/careers",
            headquarters_country="Germany",
            headquarters_city="Berlin",
            headquarters_continent="Europe",
            founded_date=d(640),
            funding_stage=FundingStage.SERIES_A,
            funding_rounds=[
                RawFundingRound(round_type="series_a", amount=12_000_000, currency="USD", amount_usd=12_000_000, announced_date=d(28), investors=[RawInvestor(name="Index Ventures", is_lead=True), RawInvestor(name="Accel")], lead_investors=["Index Ventures"], source="news"),
                RawFundingRound(round_type="seed", amount=2_400_000, currency="USD", amount_usd=2_400_000, announced_date=d(500), investors=[RawInvestor(name="Seedcamp")], source="eu_startups"),
            ],
            investors=[RawInvestor(name="Index Ventures", is_lead=True), RawInvestor(name="Accel"), RawInvestor(name="Seedcamp")],
            employee_range="51-100",
            employee_count_min=51,
            employee_count_max=100,
            estimated_employee_count=62,
            founders=["Lena Vogt"],
            primary_industry="SaaS",
            industries=["SaaS", "Enterprise"],
            business_model=["SaaS", "B2B", "Enterprise"],
            frontend_technologies=["React"],
            backend_technologies=["Node.js"],
            programming_languages=["TypeScript", "Go"],
            frameworks=["Next.js"],
            databases=["PostgreSQL"],
            cloud_providers=["GCP"],
            remote_policy=RemotePolicy.EUROPE_REMOTE,
            remote_policy_text="Remote across Europe. Optional Berlin hub.",
            remote_evidence_url="https://atlasflow.app/careers",
            remote_confidence=0.75,
            jobs=[RawJob(title="Full Stack Engineer", role_category="fullstack", location="Europe", remote_type="europe_remote", job_url="https://atlasflow.app/jobs/fullstack", source="company_site")],
            discovered_at=dt(3),
        ),
        RawCompany(
            external_id="harbor-ai",
            source_name="techcrunch",
            source_url="https://techcrunch.com/harbor-ai-seed",
            confidence=0.6,
            name="Harbor AI",
            short_description="Clinical documentation copilots for European hospitals.",
            description="Harbor AI turns clinician notes into structured EHR data. Hybrid London team with a recent Accel seed round.",
            website_url="https://harborai.health",
            careers_url="https://harborai.health/jobs",
            headquarters_country="United Kingdom",
            headquarters_city="London",
            headquarters_continent="Europe",
            founded_date=d(400),
            funding_stage=FundingStage.SEED,
            funding_rounds=[RawFundingRound(round_type="seed", amount=3_000_000, currency="GBP", amount_usd=3_810_000, announced_date=d(6), investors=[RawInvestor(name="Accel", is_lead=True)], lead_investors=["Accel"], source="techcrunch")],
            investors=[RawInvestor(name="Accel", is_lead=True)],
            employee_range="11-50",
            employee_count_min=11,
            employee_count_max=50,
            estimated_employee_count=24,
            founders=["Priya Nair", "James Okonkwo"],
            primary_industry="HealthTech",
            industries=["HealthTech", "AI"],
            business_model=["SaaS", "HealthTech", "AI"],
            programming_languages=["Python"],
            backend_technologies=["Django"],
            ai_technologies=["Anthropic"],
            databases=["PostgreSQL"],
            cloud_providers=["Azure"],
            remote_policy=RemotePolicy.HYBRID,
            remote_policy_text="Hybrid London with two office days.",
            remote_evidence_url="https://harborai.health/jobs",
            jobs=[RawJob(title="Backend Engineer", role_category="backend", location="London", remote_type="hybrid", job_url="https://harborai.health/jobs/backend", source="company_site")],
            discovered_at=dt(1),
        ),
        RawCompany(
            external_id="stacklane",
            source_name="ycombinator",
            source_url="https://www.ycombinator.com/companies/stacklane",
            confidence=0.9,
            name="Stacklane",
            short_description="Typed API platform for internal developer platforms.",
            website_url="https://stacklane.io",
            careers_url="https://stacklane.io/careers",
            yc_url="https://www.ycombinator.com/companies/stacklane",
            headquarters_country="United States",
            headquarters_city="New York",
            headquarters_continent="North America",
            founded_date=d(90),
            funding_stage=FundingStage.PRE_SEED,
            funding_rounds=[RawFundingRound(round_type="pre_seed", amount=1_200_000, currency="USD", amount_usd=1_200_000, announced_date=d(21), investors=[RawInvestor(name="Y Combinator", is_lead=True)], source="ycombinator")],
            investors=[RawInvestor(name="Y Combinator", is_lead=True)],
            employee_range="1-10",
            employee_count_min=1,
            employee_count_max=10,
            estimated_employee_count=6,
            founders=["Chris Park"],
            primary_industry="Infrastructure",
            industries=["Infrastructure", "Developer Tools"],
            business_model=["Developer Tools", "Infrastructure", "API"],
            programming_languages=["Go", "TypeScript"],
            frontend_technologies=["React"],
            backend_technologies=["Go"],
            databases=["PostgreSQL"],
            cloud_providers=["AWS"],
            devops_technologies=["Kubernetes", "Docker"],
            remote_policy=RemotePolicy.GLOBAL_REMOTE,
            remote_policy_text="Remote worldwide. No office.",
            remote_evidence_url="https://stacklane.io/careers",
            remote_confidence=0.88,
            jobs=[
                RawJob(title="Founding Frontend Engineer", role_category="frontend", location="Worldwide", remote_type="global_remote", job_url="https://stacklane.io/jobs/frontend", source="ycombinator"),
                RawJob(title="Platform Engineer", role_category="platform", location="Worldwide", remote_type="global_remote", job_url="https://stacklane.io/jobs/platform", source="ycombinator"),
            ],
            discovered_at=dt(0, 5),
        ),
        RawCompany(
            external_id="lumenpath",
            source_name="sifted",
            source_url="https://sifted.eu/articles/lumenpath-series-a",
            confidence=0.7,
            name="Lumenpath",
            short_description="Climate intelligence for industrial energy buyers.",
            website_url="https://lumenpath.eu",
            careers_url="https://lumenpath.eu/careers",
            headquarters_country="Netherlands",
            headquarters_city="Amsterdam",
            headquarters_continent="Europe",
            founded_date=d(800),
            funding_stage=FundingStage.SERIES_A,
            funding_rounds=[RawFundingRound(round_type="series_a", amount=18_000_000, currency="EUR", amount_usd=19_440_000, announced_date=d(45), investors=[RawInvestor(name="Lightspeed", is_lead=True)], lead_investors=["Lightspeed"], source="sifted")],
            investors=[RawInvestor(name="Lightspeed", is_lead=True)],
            employee_range="51-100",
            estimated_employee_count=70,
            employee_count_min=51,
            employee_count_max=100,
            founders=["Sanne de Vries"],
            primary_industry="Climate",
            industries=["Climate", "Data"],
            business_model=["SaaS", "B2B", "Data"],
            programming_languages=["Python", "TypeScript"],
            frontend_technologies=["Vue"],
            remote_policy=RemotePolicy.EMEA_REMOTE,
            remote_policy_text="Remote across EMEA.",
            jobs=[RawJob(title="Data Engineer", role_category="data", location="EMEA", remote_type="emea_remote", job_url="https://lumenpath.eu/jobs/data", source="company_site")],
            discovered_at=dt(10),
        ),
        RawCompany(
            external_id="quietline",
            source_name="producthunt",
            source_url="https://www.producthunt.com/posts/quietline",
            confidence=0.8,
            name="Quietline",
            short_description="Async communication for distributed product teams.",
            website_url="https://quietline.com",
            careers_url="https://quietline.com/jobs",
            product_hunt_url="https://www.producthunt.com/posts/quietline",
            headquarters_country="Canada",
            headquarters_city="Toronto",
            headquarters_continent="North America",
            founded_date=d(18),
            product_launch_date=d(2),
            funding_stage=FundingStage.BOOTSTRAPPED,
            employee_range="1-10",
            employee_count_min=1,
            employee_count_max=10,
            estimated_employee_count=4,
            founders=["Elena Rossi"],
            primary_industry="SaaS",
            industries=["SaaS", "Collaboration"],
            business_model=["SaaS", "B2B"],
            programming_languages=["TypeScript"],
            frontend_technologies=["React", "Next.js"],
            backend_technologies=["Node.js"],
            frameworks=["Next.js"],
            remote_policy=RemotePolicy.REMOTE_FIRST,
            remote_policy_text="Remote-first, async team. Work from anywhere with overlap in GMT-5 to GMT+2.",
            remote_evidence_url="https://quietline.com/about",
            jobs=[RawJob(title="Full Stack Engineer", role_category="fullstack", location="Remote", remote_type="remote_first", job_url="https://quietline.com/jobs/fullstack", source="producthunt")],
            discovered_at=dt(2),
        ),
        RawCompany(
            external_id="vectornest",
            source_name="andreessen_horowitz",
            source_url="https://a16z.com/portfolio/vectornest",
            confidence=0.8,
            name="Vectornest",
            short_description="Managed vector database for AI application teams.",
            website_url="https://vectornest.ai",
            careers_url="https://vectornest.ai/careers",
            headquarters_country="Canada",
            headquarters_city="Toronto",
            headquarters_continent="North America",
            founded_date=d(300),
            funding_stage=FundingStage.SEED,
            funding_rounds=[RawFundingRound(round_type="seed", amount=6_000_000, currency="USD", amount_usd=6_000_000, announced_date=d(9), investors=[RawInvestor(name="Andreessen Horowitz", is_lead=True)], lead_investors=["Andreessen Horowitz"], source="funding")],
            investors=[RawInvestor(name="Andreessen Horowitz", is_lead=True)],
            employee_range="11-50",
            estimated_employee_count=22,
            employee_count_min=11,
            employee_count_max=50,
            founders=["Noah Kim"],
            primary_industry="Infrastructure",
            industries=["Infrastructure", "AI", "Data"],
            business_model=["Infrastructure", "AI", "API"],
            programming_languages=["Rust", "Python"],
            backend_technologies=["Python"],
            databases=["PostgreSQL"],
            cloud_providers=["AWS"],
            remote_policy=RemotePolicy.GLOBAL_REMOTE,
            remote_policy_text="Hire globally. Worldwide remote.",
            jobs=[
                RawJob(title="Rust Engineer", role_category="backend", location="Worldwide", remote_type="global_remote", job_url="https://vectornest.ai/jobs/rust", source="company_site"),
                RawJob(title="DevOps Engineer", role_category="devops", location="Worldwide", remote_type="global_remote", job_url="https://vectornest.ai/jobs/devops", source="company_site"),
            ],
            discovered_at=dt(4),
        ),
        RawCompany(
            external_id="folioforge",
            source_name="sequoia",
            source_url="https://www.sequoiacap.com/companies/folioforge",
            confidence=0.8,
            name="Folioforge",
            short_description="Embedded finance infrastructure for vertical SaaS.",
            website_url="https://folioforge.com",
            careers_url="https://folioforge.com/careers",
            headquarters_country="Singapore",
            headquarters_city="Singapore",
            headquarters_continent="Asia",
            founded_date=d(1200),
            funding_stage=FundingStage.SERIES_B,
            funding_rounds=[RawFundingRound(round_type="series_b", amount=40_000_000, currency="USD", amount_usd=40_000_000, announced_date=d(70), investors=[RawInvestor(name="Sequoia", is_lead=True), RawInvestor(name="Lightspeed")], lead_investors=["Sequoia"], source="sequoia")],
            investors=[RawInvestor(name="Sequoia", is_lead=True), RawInvestor(name="Lightspeed")],
            employee_range="201-500",
            estimated_employee_count=240,
            employee_count_min=201,
            employee_count_max=500,
            founders=["Wei Tan"],
            primary_industry="FinTech",
            industries=["FinTech", "Infrastructure"],
            business_model=["FinTech", "B2B", "API"],
            programming_languages=["Java", "TypeScript"],
            backend_technologies=["Spring Boot"],
            remote_policy=RemotePolicy.HYBRID,
            jobs=[RawJob(title="Staff Backend Engineer", role_category="backend", location="Singapore", remote_type="hybrid", job_url="https://folioforge.com/jobs/backend", source="company_site")],
            discovered_at=dt(20),
        ),
        RawCompany(
            external_id="driftmail",
            source_name="seedcamp",
            source_url="https://seedcamp.com/portfolio/driftmail",
            confidence=0.75,
            name="Driftmail",
            short_description="Email infrastructure for product-led SaaS companies.",
            website_url="https://driftmail.io",
            careers_url="https://driftmail.io/jobs",
            headquarters_country="Ireland",
            headquarters_city="Dublin",
            headquarters_continent="Europe",
            founded_date=d(260),
            funding_stage=FundingStage.SEED,
            funding_rounds=[RawFundingRound(round_type="seed", amount=2_500_000, currency="EUR", amount_usd=2_700_000, announced_date=d(16), investors=[RawInvestor(name="Seedcamp", is_lead=True)], source="seedcamp")],
            investors=[RawInvestor(name="Seedcamp", is_lead=True)],
            employee_range="1-10",
            estimated_employee_count=9,
            employee_count_min=1,
            employee_count_max=10,
            founders=["Aoife Byrne"],
            primary_industry="Developer Tools",
            industries=["Developer Tools", "Infrastructure"],
            business_model=["SaaS", "Developer Tools", "API"],
            programming_languages=["TypeScript", "Go"],
            frontend_technologies=["Next.js"],
            backend_technologies=["Node.js"],
            frameworks=["Next.js"],
            databases=["PostgreSQL", "Redis"],
            remote_policy=RemotePolicy.GLOBAL_REMOTE,
            remote_policy_text="Fully remote. Work from anywhere.",
            jobs=[RawJob(title="Backend Engineer", role_category="backend", location="Worldwide", remote_type="global_remote", job_url="https://driftmail.io/jobs/backend", source="company_site")],
            discovered_at=dt(5),
        ),
        RawCompany(
            external_id="pixelwright",
            source_name="hackernews",
            source_url="https://news.ycombinator.com/item?id=pixelwright",
            confidence=0.55,
            name="Pixelwright",
            short_description="Collaborative design editor launched this month on Hacker News.",
            website_url="https://pixelwright.app",
            product_launch_date=d(4),
            headquarters_country="France",
            headquarters_city="Paris",
            headquarters_continent="Europe",
            founded_date=d(40),
            funding_stage=FundingStage.PRE_SEED,
            funding_rounds=[RawFundingRound(round_type="pre_seed", amount=800_000, currency="EUR", amount_usd=864_000, announced_date=d(25), investors=[RawInvestor(name="Antler")], source="hackernews")],
            investors=[RawInvestor(name="Antler")],
            employee_range="1-10",
            estimated_employee_count=5,
            employee_count_min=1,
            employee_count_max=10,
            founders=["Camille Laurent"],
            primary_industry="Design",
            industries=["Design", "SaaS"],
            business_model=["SaaS", "Consumer"],
            programming_languages=["TypeScript"],
            frontend_technologies=["React", "Svelte"],
            remote_policy=RemotePolicy.REMOTE_FIRST,
            jobs=[RawJob(title="Frontend Engineer", role_category="frontend", location="Remote", remote_type="remote_first", job_url="https://pixelwright.app/jobs", source="hackernews")],
            discovered_at=dt(4),
        ),
        RawCompany(
            external_id="orbitdesk",
            source_name="wellfound",
            source_url="https://wellfound.com/company/orbitdesk",
            confidence=0.5,
            name="Orbitdesk",
            short_description="Customer success workspace for PLG companies.",
            website_url="https://orbitdesk.com",
            careers_url="https://orbitdesk.com/careers",
            wellfound_url="https://wellfound.com/company/orbitdesk",
            headquarters_country="United States",
            headquarters_city="Austin",
            headquarters_continent="North America",
            founded_date=d(500),
            funding_stage=FundingStage.SERIES_A,
            funding_rounds=[RawFundingRound(round_type="series_a", amount=14_000_000, currency="USD", amount_usd=14_000_000, announced_date=d(33), investors=[RawInvestor(name="Bessemer", is_lead=True), RawInvestor(name="General Catalyst")], lead_investors=["Bessemer"], source="wellfound")],
            investors=[RawInvestor(name="Bessemer", is_lead=True), RawInvestor(name="General Catalyst")],
            employee_range="51-100",
            estimated_employee_count=80,
            employee_count_min=51,
            employee_count_max=100,
            founders=["Jordan Blake"],
            primary_industry="SaaS",
            industries=["SaaS", "Customer Success"],
            business_model=["SaaS", "B2B"],
            programming_languages=["Ruby", "TypeScript"],
            backend_technologies=["Rails"],
            frameworks=["Rails"],
            frontend_technologies=["React"],
            remote_policy=RemotePolicy.US_REMOTE,
            remote_policy_text="US remote. Overlap with Austin hours required.",
            jobs=[RawJob(title="Senior Rails Engineer", role_category="backend", location="United States", remote_type="us_remote", job_url="https://orbitdesk.com/jobs/rails", source="wellfound")],
            discovered_at=dt(8),
        ),
        RawCompany(
            external_id="nimbusforge",
            source_name="ycombinator",
            source_url="https://www.ycombinator.com/companies/nimbusforge",
            confidence=0.9,
            name="NimbusForge",
            short_description="Multiplayer game infrastructure for indie studios.",
            website_url="https://nimbusforge.gg",
            careers_url="https://nimbusforge.gg/jobs",
            yc_url="https://www.ycombinator.com/companies/nimbusforge",
            headquarters_country="Sweden",
            headquarters_city="Stockholm",
            headquarters_continent="Europe",
            founded_date=d(70),
            funding_stage=FundingStage.SEED,
            funding_rounds=[RawFundingRound(round_type="seed", amount=3_800_000, currency="USD", amount_usd=3_800_000, announced_date=d(3), investors=[RawInvestor(name="Y Combinator", is_lead=True), RawInvestor(name="Benchmark")], source="ycombinator")],
            investors=[RawInvestor(name="Y Combinator", is_lead=True), RawInvestor(name="Benchmark")],
            employee_range="11-50",
            estimated_employee_count=14,
            employee_count_min=11,
            employee_count_max=50,
            founders=["Erik Holm"],
            primary_industry="Gaming",
            industries=["Gaming", "Infrastructure"],
            business_model=["Infrastructure", "API"],
            programming_languages=["Rust", "Go"],
            remote_policy=RemotePolicy.GLOBAL_REMOTE,
            remote_policy_text="Distributed team. Remote worldwide.",
            jobs=[RawJob(title="Multiplayer Engineer", role_category="backend", location="Worldwide", remote_type="global_remote", job_url="https://nimbusforge.gg/jobs/multiplayer", source="ycombinator")],
            discovered_at=dt(0, 1),
        ),
        RawCompany(
            external_id="redwood-robotics",
            source_name="eu_startups",
            source_url="https://www.eu-startups.com/redwood-robotics",
            confidence=0.65,
            name="Redwood Robotics",
            short_description="Warehouse robotics software for European logistics.",
            website_url="https://redwoodrobotics.de",
            headquarters_country="Germany",
            headquarters_city="Munich",
            headquarters_continent="Europe",
            founded_date=d(900),
            funding_stage=FundingStage.SERIES_A,
            funding_rounds=[RawFundingRound(round_type="series_a", amount=22_000_000, currency="EUR", amount_usd=23_760_000, announced_date=d(55), investors=[RawInvestor(name="Index Ventures", is_lead=True)], source="eu_startups")],
            investors=[RawInvestor(name="Index Ventures", is_lead=True)],
            employee_range="101-200",
            estimated_employee_count=120,
            employee_count_min=101,
            employee_count_max=200,
            founders=["Anja Keller"],
            primary_industry="Robotics",
            industries=["Robotics", "Logistics"],
            business_model=["Robotics", "Enterprise"],
            programming_languages=["C++", "Python"],
            remote_policy=RemotePolicy.ONSITE,
            remote_policy_text="On-site Munich hardware lab required.",
            office_required=True,
            discovered_at=dt(15),
        ),
        RawCompany(
            external_id="paperclip-ai",
            source_name="techcrunch",
            source_url="https://techcrunch.com/paperclip-ai-funding",
            confidence=0.6,
            name="Paperclip AI",
            short_description="Contract review copilots for in-house legal teams.",
            website_url="https://paperclip.ai",
            careers_url="https://paperclip.ai/careers",
            headquarters_country="United States",
            headquarters_city="Boston",
            headquarters_continent="North America",
            founded_date=d(150),
            funding_stage=FundingStage.SEED,
            funding_rounds=[RawFundingRound(round_type="seed", amount=5_500_000, currency="USD", amount_usd=5_500_000, announced_date=d(1), investors=[RawInvestor(name="GV", is_lead=True), RawInvestor(name="Khosla Ventures")], lead_investors=["GV"], source="techcrunch")],
            investors=[RawInvestor(name="GV", is_lead=True), RawInvestor(name="Khosla Ventures")],
            employee_range="11-50",
            estimated_employee_count=16,
            employee_count_min=11,
            employee_count_max=50,
            founders=["Rachel Stein"],
            primary_industry="LegalTech",
            industries=["LegalTech", "AI"],
            business_model=["SaaS", "AI", "Enterprise"],
            programming_languages=["Python", "TypeScript"],
            frontend_technologies=["Next.js"],
            backend_technologies=["FastAPI"],
            ai_technologies=["OpenAI", "Anthropic"],
            remote_policy=RemotePolicy.REMOTE_FIRST,
            remote_policy_text="Remote-first with a Boston meetup every quarter.",
            jobs=[
                RawJob(title="AI Engineer", role_category="ai", location="Remote", remote_type="remote_first", job_url="https://paperclip.ai/jobs/ai", source="company_site"),
                RawJob(title="Full Stack Engineer", role_category="fullstack", location="Remote", remote_type="remote_first", job_url="https://paperclip.ai/jobs/fullstack", source="company_site"),
            ],
            discovered_at=dt(0, 3),
        ),
        RawCompany(
            external_id="campfire-labs",
            source_name="producthunt",
            source_url="https://www.producthunt.com/posts/campfire-labs",
            confidence=0.7,
            name="Campfire Labs",
            short_description="Lightweight onboarding for developer tools companies.",
            website_url="https://campfirelabs.dev",
            product_hunt_url="https://www.producthunt.com/posts/campfire-labs",
            product_launch_date=d(0),
            headquarters_country="Portugal",
            headquarters_city="Lisbon",
            headquarters_continent="Europe",
            founded_date=d(8),
            funding_stage=FundingStage.PRE_SEED,
            funding_rounds=[RawFundingRound(round_type="pre_seed", amount=600_000, currency="EUR", amount_usd=648_000, announced_date=d(7), investors=[RawInvestor(name="Antler")], source="producthunt")],
            investors=[RawInvestor(name="Antler")],
            employee_range="1-10",
            estimated_employee_count=3,
            employee_count_min=1,
            employee_count_max=10,
            founders=["Miguel Costa"],
            primary_industry="Developer Tools",
            industries=["Developer Tools", "SaaS"],
            business_model=["SaaS", "Developer Tools"],
            programming_languages=["TypeScript"],
            frontend_technologies=["React", "Next.js"],
            backend_technologies=["Node.js"],
            remote_policy=RemotePolicy.GLOBAL_REMOTE,
            remote_policy_text="Worldwide remote. Work from anywhere.",
            jobs=[RawJob(title="Founding Engineer", role_category="fullstack", location="Worldwide", remote_type="global_remote", job_url="https://campfirelabs.dev/jobs", source="producthunt")],
            discovered_at=dt(0, 1),
        ),
        RawCompany(
            external_id="keelsecurity",
            source_name="techstars",
            source_url="https://www.techstars.com/portfolio/keelsecurity",
            confidence=0.7,
            name="Keel Security",
            short_description="Runtime cloud security for early-stage SaaS.",
            website_url="https://keelsecurity.com",
            careers_url="https://keelsecurity.com/careers",
            headquarters_country="United States",
            headquarters_city="Denver",
            headquarters_continent="North America",
            founded_date=d(310),
            funding_stage=FundingStage.SEED,
            funding_rounds=[RawFundingRound(round_type="seed", amount=4_000_000, currency="USD", amount_usd=4_000_000, announced_date=d(80), investors=[RawInvestor(name="Techstars", is_lead=True), RawInvestor(name="Founders Fund")], source="techstars")],
            investors=[RawInvestor(name="Techstars", is_lead=True), RawInvestor(name="Founders Fund")],
            employee_range="11-50",
            estimated_employee_count=19,
            employee_count_min=11,
            employee_count_max=50,
            founders=["Devon Price"],
            primary_industry="Security",
            industries=["Security", "Cloud"],
            business_model=["SaaS", "Security", "B2B"],
            programming_languages=["Go", "Python"],
            devops_technologies=["Kubernetes", "Terraform"],
            cloud_providers=["AWS", "GCP"],
            remote_policy=RemotePolicy.US_REMOTE,
            jobs=[RawJob(title="Security Engineer", role_category="security", location="United States", remote_type="us_remote", job_url="https://keelsecurity.com/jobs/security", source="techstars")],
            discovered_at=dt(12),
        ),
    ]


SAVED_VIEWS = [
    {"name": "Global Remote AI Startups", "description": "Worldwide remote companies in AI", "filters": {"remote_policy": "GLOBAL_REMOTE", "industry": "AI", "sort": "opportunity_score"}},
    {"name": "Seed Startups Hiring Engineers", "description": "Seed-stage teams actively hiring engineers", "filters": {"funding_stage": "seed", "hiring_engineers": True, "sort": "latest_funding"}},
    {"name": "Recently Funded Under 50 Employees", "description": "Small teams with fresh capital", "filters": {"employee_max": 50, "sort": "latest_funding"}},
    {"name": "New Startups Using React + Node", "description": "JavaScript-heavy product teams", "filters": {"technology": "React", "sort": "newest_discovered"}},
    {"name": "Series A Global Remote", "description": "Series A companies that hire worldwide", "filters": {"funding_stage": "series_a", "remote_policy": "GLOBAL_REMOTE", "sort": "opportunity_score"}},
]


def seed() -> None:
    session = SessionLocal()
    try:
        existing = session.scalar(select(Company.id).limit(1))
        if existing:
            print("Database already has companies; skipping seed.")
            return
        for raw in companies():
            ingest_raw_company(session, raw)
        for view in SAVED_VIEWS:
            if session.scalar(select(SavedView).where(SavedView.name == view["name"])) is None:
                session.add(SavedView(**view))
        session.commit()
        print(f"Seeded {len(companies())} companies.")
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


if __name__ == "__main__":
    seed()
