from __future__ import annotations

from datetime import UTC, date, datetime, timedelta

from models.enums import FundingStage, RemotePolicy
from models.raw_company import RawCompany, RawFundingRound, RawInvestor, RawJob
from sources.base import StartupSource


class FixtureSource(StartupSource):
    """Deterministic demo source used for tests and the manual scraper button."""

    name = "fixture"
    category = "startup_directories"
    description = "Built-in fixture source that inserts a newly discovered company on each run."

    async def discover(self) -> list[RawCompany]:
        stamp = datetime.now(UTC).strftime("%Y%m%d%H%M")
        name = f"Radar Beacon {stamp}"
        domain = f"radarbeacon-{stamp}.dev"
        return [
            RawCompany(
                external_id=f"fixture-{stamp}",
                source_name=self.name,
                source_url="https://startup-radar.local/fixtures",
                confidence=0.99,
                name=name,
                short_description="Synthetic remote-first developer tools company used to verify ingestion.",
                description=(
                    "Radar Beacon is a fixture company generated by the Startup Radar scraper. "
                    "It exists so newly discovered companies can be verified end-to-end."
                ),
                website_url=f"https://{domain}",
                careers_url=f"https://{domain}/careers",
                jobs_url=f"https://{domain}/jobs",
                headquarters_country="Ireland",
                headquarters_city="Dublin",
                headquarters_continent="Europe",
                founded_date=date.today() - timedelta(days=40),
                funding_stage=FundingStage.SEED,
                latest_funding_amount=3_200_000,
                latest_funding_currency="USD",
                latest_funding_usd=3_200_000,
                latest_funding_date=date.today(),
                funding_rounds=[
                    RawFundingRound(
                        round_type="seed",
                        amount=3_200_000,
                        currency="USD",
                        amount_usd=3_200_000,
                        announced_date=date.today(),
                        investors=[RawInvestor(name="Seedcamp", investor_type="accelerator", is_lead=True)],
                        lead_investors=["Seedcamp"],
                        source=self.name,
                    )
                ],
                investors=[RawInvestor(name="Seedcamp", investor_type="accelerator", is_lead=True)],
                employee_range="1-10",
                employee_count_min=1,
                employee_count_max=10,
                estimated_employee_count=8,
                founders=["Ada Lovelace"],
                primary_industry="Developer Tools",
                industries=["Developer Tools", "AI"],
                business_model=["SaaS", "Developer Tools", "AI"],
                programming_languages=["TypeScript", "Python"],
                frontend_technologies=["React", "Next.js"],
                backend_technologies=["FastAPI"],
                frameworks=["Next.js", "FastAPI"],
                databases=["PostgreSQL", "Redis"],
                cloud_providers=["AWS"],
                remote_policy=RemotePolicy.GLOBAL_REMOTE,
                remote_policy_text="Work from anywhere. Fully remote worldwide.",
                remote_evidence_url=f"https://{domain}/careers",
                remote_confidence=0.9,
                jobs=[
                    RawJob(
                        title="Senior Backend Engineer",
                        role_category="backend",
                        location="Worldwide",
                        remote_type="global_remote",
                        job_url=f"https://{domain}/jobs/backend",
                        source=self.name,
                    )
                ],
                source_urls=[f"https://{domain}"],
                tech_stack_confidence=0.8,
            )
        ]
